<a href="https://colab.research.google.com/github/haneeth25/Libraries_prac/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [124]:
#numpy
import numpy as np

In [189]:
# 3d array
a = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]],dtype = 'int16')
b = np.array([[1,2,3,4,20],[5,6,7,8,40]])
c = np.array([[9,10,11,12],[13,14,15,16]])
d =  np.array([[1,2],[5,6],[25,2],[10,120]])
e = np.array([[9,10,11,12],[13,14,15,16]])

In [126]:
a.shape

(2, 2, 3)

In [127]:
a.ndim

3

In [154]:
b.shape

(2, 5)

In [129]:
c.shape

(2, 4)

In [130]:
b.ndim

2

In [131]:
len(a.shape) == a.ndim

True

In [132]:
# No of elements
a.size

12

In [133]:
a[0][1][2]

6

In [134]:
a.dtype

dtype('int16')

In [135]:
np.zeros(2)

array([0., 0.])

In [136]:
np.ones(2)

array([1., 1.])

In [137]:
np.arange(4,10,2) # (start,end,step)

array([4, 6, 8])

In [138]:
np.linspace(0,10,num=5) # provide linearspace between number

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [139]:
z = np.concatenate((b,c),axis = 1);

In [140]:
z

array([[ 1,  2,  3,  4, 20,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 40, 13, 14, 15, 16]])

In [141]:
z.shape

(2, 9)

In [142]:
z = np.concatenate((d,e),axis = 0);

In [143]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [25,  2,  5, 23],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [144]:
z.shape

(5, 4)

In [145]:
e = np.arange(6)

In [146]:
e

array([0, 1, 2, 3, 4, 5])

In [147]:
a.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]], dtype=int16)

In [171]:
e = np.expand_dims(b,axis = 1)
e = np.expand_dims(e,axis = 0)
e.shape

(1, 2, 1, 5)

In [172]:
e

array([[[[ 1,  2,  3,  4, 20]],

        [[ 5,  6,  7,  8, 40]]]])

In [184]:
c+e

array([[18, 20, 22, 24],
       [26, 28, 30, 32]])

In [191]:
c*e

array([[ 81, 100, 121, 144],
       [169, 196, 225, 256]])