<a href="https://colab.research.google.com/github/haneeth25/Libraries_prac/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#numpy
import numpy as np

In [31]:
# 3d array
a = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]],dtype = 'int16')
b = np.array([[1,2,3,4],[5,6,7,8]])

In [32]:
a.shape

(2, 2, 3)

In [33]:
a.ndim

3

In [34]:
b.shape

(2, 4)

In [35]:
b.ndim

2

In [36]:
len(a.shape) == a.ndim

True

In [40]:
# No of elements
a.size

12

In [41]:
a[0][1][2]

6

In [42]:
a.dtype

dtype('int16')

In [43]:
np.zeros(2)

array([0., 0.])

In [44]:
np.ones(2)

array([1., 1.])

In [50]:
np.arange(4,10,2) # (start,end,step)

array([4, 6, 8])

In [53]:
np.linspace(0,10,num=5) # provide linearspace between number

array([ 0. ,  2.5,  5. ,  7.5, 10. ])