<a href="https://colab.research.google.com/github/haneeth25/Libraries_prac/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#numpy
import numpy as np

In [245]:
# 3d array
a = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,12]]],dtype = 'int16')
b = np.array([[1,2,3,4,20],[5,6,7,8,40]])
c = np.array([[9,10,11,12],[13,14,15,16]])
d =  np.array([[1,2],[5,6],[25,2],[10,120]])
e = np.array([[9,10,11,12],[13,14,15,16]])

In [244]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 12]]], dtype=int16)

In [ ]:
a.ndim

3

In [ ]:
b.shape

(2, 5)

In [ ]:
c.shape

(2, 4)

In [ ]:
b.ndim

2

In [ ]:
len(a.shape) == a.ndim

True

In [ ]:
# No of elements
a.size

12

In [ ]:
a[0][1][2]

6

In [ ]:
a.dtype

dtype('int16')

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.arange(4,10,2) # (start,end,step)

array([4, 6, 8])

In [ ]:
np.linspace(0,10,num=5) # provide linearspace between number

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
z = np.concatenate((b,c),axis = 1);

In [ ]:
z

array([[ 1,  2,  3,  4, 20,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 40, 13, 14, 15, 16]])

In [ ]:
z.shape

(2, 9)

In [ ]:
z = np.concatenate((d,e),axis = 0);

In [ ]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [25,  2,  5, 23],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
z.shape

(5, 4)

In [ ]:
e = np.arange(6)

In [ ]:
e

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]], dtype=int16)

In [ ]:
e = np.expand_dims(b,axis = 1)
e = np.expand_dims(e,axis = 0)
e.shape

(1, 2, 1, 5)

In [ ]:
e

array([[[[ 1,  2,  3,  4, 20]],

        [[ 5,  6,  7,  8, 40]]]])

In [ ]:
c+e

array([[18, 20, 22, 24],
       [26, 28, 30, 32]])

In [ ]:
c*e

array([[ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [ ]:
data = np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

In [ ]:
data.max()
data.min()
data.sum()

3.0

In [ ]:
a[0].min(axis = 1)

array([1, 4], dtype=int16)

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data.min(axis = 1)

array([1, 3, 4])

In [ ]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12], dtype=int16)

In [ ]:
unique_values,occurence_count = np.unique(a,return_counts = True,axis = 0);
n = len(unique_values)
for i in range(n):
    print(unique_values[i],occurence_count[i])

[[1 2 3]
 [4 5 6]] 1
[[ 8  9 10]
 [11 12 12]] 1


In [238]:
y = np.flip(a[0])
y.shape
x = np.concatenate((y,a[1]),axis = 1)
a[1]

array([[ 8,  9, 10],
       [11, 12, 12]], dtype=int16)

In [236]:
y

array([[6, 5, 4],
       [3, 2, 1]], dtype=int16)

In [237]:
x

array([[ 6,  5,  4,  8,  9, 10],
       [ 3,  2,  1, 11, 12, 12]], dtype=int16)

In [239]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [256]:
a[0]

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [263]:
a[0] = np.flip(a[0])

In [264]:
a

array([[[ 6,  5,  4],
        [ 3,  2,  1]],

       [[ 8,  9, 10],
        [11, 12, 12]]], dtype=int16)

In [266]:
# flatten,ravel
a

array([[[ 6,  5,  4],
        [ 3,  2,  1]],

       [[ 8,  9, 10],
        [11, 12, 12]]], dtype=int16)

In [267]:
a1 = a.flatten()

In [268]:
a1

array([ 6,  5,  4,  3,  2,  1,  8,  9, 10, 11, 12, 12], dtype=int16)

In [269]:
a1[3] = 100

In [271]:
a

array([[[ 6,  5,  4],
        [ 3,  2,  1]],

       [[ 8,  9, 10],
        [11, 12, 12]]], dtype=int16)

In [272]:
a2 = a.ravel()

In [273]:
a2

array([ 6,  5,  4,  3,  2,  1,  8,  9, 10, 11, 12, 12], dtype=int16)

In [274]:
a2[2] = 100

In [276]:
a
# Main array also changes if you use ravel

array([[[  6,   5, 100],
        [  3,   2,   1]],

       [[  8,   9,  10],
        [ 11,  12,  12]]], dtype=int16)