<a href="https://colab.research.google.com/github/haneeth25/Libraries_prac/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
#numpy
import numpy as np

In [114]:
# 3d array
a = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]],dtype = 'int16')
b = np.array([[1,2,3,4,20],[5,6,7,8,40]])
c = np.array([[9,10,11,12],[13,14,15,16]])
d =  np.array([[1,2,3,4],[5,6,7,8],[25,2,5,23]])
e = np.array([[9,10,11,12],[13,14,15,16]])

In [72]:
a.shape

(2, 2, 3)

In [58]:
a.ndim

3

In [90]:
b.shape

(2, 4)

In [91]:
c.shape

(2, 4)

In [60]:
b.ndim

2

In [61]:
len(a.shape) == a.ndim

True

In [62]:
# No of elements
a.size

12

In [63]:
a[0][1][2]

6

In [64]:
a.dtype

dtype('int16')

In [65]:
np.zeros(2)

array([0., 0.])

In [66]:
np.ones(2)

array([1., 1.])

In [67]:
np.arange(4,10,2) # (start,end,step)

array([4, 6, 8])

In [68]:
np.linspace(0,10,num=5) # provide linearspace between number

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [100]:
z = np.concatenate((b,c),axis = 1);

In [101]:
z

array([[ 1,  2,  3,  4, 20,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 40, 13, 14, 15, 16]])

In [102]:
z.shape

(2, 9)

In [103]:
z = np.concatenate((d,e),axis = 0);

In [106]:
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [25,  2,  5, 23],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [105]:
z.shape

(5, 4)

In [110]:
e = np.arange(6)

In [111]:
e

array([0, 1, 2, 3, 4, 5])

In [123]:
a.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 8,  9]],

       [[10, 11],
        [12, 13]]], dtype=int16)